Style/StringLiterals:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/Documentation:
  Enabled: false
